# Generated by Django 5.1.1 on 2024-10-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shilppingPrice',
            new_name='shippingPrice',
        ),
    ]
